# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
      - master
      - release-**
  pull_request:
    branches:
      - master
      - release-**

jobs:
  testing:
    name: Code quality and testing
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Run Android Linter
        run: ./gradlew :pinkman:lint :pinkman-ui:lint

      - name: Run Detekt
        run: ./gradlew detekt

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Android Emulator Runner
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck
      
